
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        default_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/login
            provider: default_provider
            guard:
                authenticators:
                    - AppBundle\Security\ApiLoginAuthenticator

        main:
            pattern: ^/
            anonymous: ~
            provider: default_provider
            guard:
                authenticators:
                    - AppBundle\Security\FormLoginAuthenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
